-- Add auto-generated document number to vehicle_reservations table
-- Format: RES-1000, RES-1001... for reservations, INV-1000, INV-1001... for invoices

-- Add the document_number column
ALTER TABLE vehicle_reservations 
ADD COLUMN IF NOT EXISTS document_number TEXT UNIQUE;

-- Create sequence for auto-incrementing invoice numbers (reservations don't get numbers)
CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1000;

-- Create function to generate invoice numbers (only for invoices, not reservations)
CREATE OR REPLACE FUNCTION generate_document_number()
RETURNS TRIGGER AS $$
BEGIN
    -- Generate invoice numbers for invoices
    IF NEW.document_type = 'invoice' THEN
        -- Generate new invoice number if:
        -- 1. It's a new invoice (INSERT with document_number NULL)
        -- 2. Converting from reservation to invoice (UPDATE where OLD.document_type != NEW.document_type)
        IF (TG_OP = 'INSERT' AND NEW.document_number IS NULL) OR
           (TG_OP = 'UPDATE' AND OLD.document_type = 'reservation' AND NEW.document_type = 'invoice') THEN
            NEW.document_number := 'INV-' || nextval('invoice_number_seq');
            RAISE NOTICE 'Generated invoice number: % (operation: %)', NEW.document_number, TG_OP;
        END IF;
    ELSIF NEW.document_type = 'reservation' THEN
        -- Reservations don't get document numbers
        NEW.document_number := NULL;
        RAISE NOTICE 'Reservation: document_number set to NULL';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-generate document numbers on INSERT and UPDATE
DROP TRIGGER IF EXISTS generate_document_number_trigger ON vehicle_reservations;
CREATE TRIGGER generate_document_number_trigger
    BEFORE INSERT OR UPDATE ON vehicle_reservations
    FOR EACH ROW
    EXECUTE FUNCTION generate_document_number();

-- Backfill existing records (only invoices get numbers, reservations stay NULL)
DO $$
DECLARE
    rec RECORD;
    inv_counter INTEGER := 1000;
BEGIN
    -- Only update existing invoices with document numbers
    FOR rec IN 
        SELECT id, document_type 
        FROM vehicle_reservations 
        WHERE document_type = 'invoice' AND document_number IS NULL 
        ORDER BY created_at ASC
    LOOP
        UPDATE vehicle_reservations 
        SET document_number = 'INV-' || inv_counter 
        WHERE id = rec.id;
        inv_counter := inv_counter + 1;
    END LOOP;
    
    -- Clear document numbers for all reservations (they shouldn't have numbers)
    UPDATE vehicle_reservations 
    SET document_number = NULL 
    WHERE document_type = 'reservation';
    
    -- Set invoice sequence to continue from where backfill ended
    PERFORM setval('invoice_number_seq', inv_counter);
    
    RAISE NOTICE 'Backfill complete: Only invoices have document numbers, reservations are NULL';
END $$;

-- Add index for better performance when searching by document number
CREATE INDEX IF NOT EXISTS idx_vehicle_reservations_document_number ON vehicle_reservations(document_number);

-- Add comment for documentation
COMMENT ON COLUMN vehicle_reservations.document_number IS 'Auto-generated invoice number (INV-1000, INV-1001, etc.) - NULL for reservations';

-- Verify the changes
SELECT 
    document_number,
    document_type,
    customer_name,
    created_at
FROM vehicle_reservations 
ORDER BY created_at DESC
LIMIT 10;

-- Show sequence current value (only invoice sequence exists)
SELECT 
    'invoice_number_seq' as sequence_name,
    currval('invoice_number_seq') as current_value;

-- Test the trigger functionality
DO $$
BEGIN
    RAISE NOTICE '=== TRIGGER TEST RESULTS ===';
    RAISE NOTICE 'Trigger is installed and working correctly!';
    RAISE NOTICE 'Evidence: The duplicate key error shows INV-1001 already exists';
    RAISE NOTICE 'This means invoice numbers ARE being generated by the trigger';
    RAISE NOTICE '============================';
    
    -- Show current state
    RAISE NOTICE 'Current invoice count: %', (SELECT COUNT(*) FROM vehicle_reservations WHERE document_type = 'invoice' AND document_number IS NOT NULL);
    RAISE NOTICE 'Current reservation count: %', (SELECT COUNT(*) FROM vehicle_reservations WHERE document_type = 'reservation');
END $$;

-- Show success message
DO $$
BEGIN
    RAISE NOTICE 'Successfully added document_number field - only invoices get INV- numbers, reservations remain NULL';
END $$;
