-- Fix Sales Department RLS Policies
-- The current policies only check can_view, but for INSERT/UPDATE we need can_edit

-- Drop existing policies
DROP POLICY IF EXISTS "sales_targets_policy" ON sales_monthly_targets;
DROP POLICY IF EXISTS "sales_inputs_policy" ON sales_daily_inputs;
DROP POLICY IF EXISTS "sales_calculations_policy" ON sales_calculated_metrics;

-- Recreate with proper permissions

-- Sales Targets: Users with accounts module edit permissions can manage targets
CREATE POLICY "sales_targets_policy" ON sales_monthly_targets FOR ALL USING (
    EXISTS (
        SELECT 1 FROM get_user_module_permissions(auth.uid(), 'accounts') 
        WHERE can_edit = true
    )
);

-- Sales Daily Inputs: Users with accounts module edit permissions can manage daily inputs
CREATE POLICY "sales_inputs_policy" ON sales_daily_inputs FOR ALL USING (
    EXISTS (
        SELECT 1 FROM get_user_module_permissions(auth.uid(), 'accounts') 
        WHERE can_edit = true
    )
);

-- Sales Calculated Metrics: Users with accounts or uv_crm view permissions can read calculated metrics
-- Note: This table is auto-generated by the calculate_sales_metrics function, so it only needs SELECT
CREATE POLICY "sales_calculations_policy" ON sales_calculated_metrics FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM get_user_module_permissions(auth.uid(), 'accounts') 
        WHERE can_view = true
    )
    OR EXISTS (
        SELECT 1 FROM get_user_module_permissions(auth.uid(), 'uv_crm') 
        WHERE can_view = true
    )
);

SELECT 'Sales RLS policies fixed successfully!' as status; 